### ISSUE TITLE
Why my app crash when i click button share community

### ISSUE THREAD

**Issue by NguyenVanSao** [aiguoli/SimpleList#8]

**Comment by NguyenVanSao** [comment]
![image](https://github.com/user-attachments/assets/daf85bc6-2eec-40ec-a6bd-e8ea3cc391eb)

**Comment by aiguoli** [comment]
Since the SSL certificate of this service site had expired, it has now been restored. If you desire a more stable service, you may consider setting up a new service by yourself. The code of service is available [here](https://github.com/aiguoli/link-share) and then configure it within the `SimpleList/appsettings.json` file. 

Meanwhile, developers are also welcomed to develop plugins and submit them to the repository.

**Comment by NguyenVanSao** [comment]
Thanks you for your reply
